### ISSUE TITLE
No interfaces loading in the patchbay

### ISSUE THREAD

**Issue by CommanderRedYT** [Houston4444/RaySession#231] opened 2024-06-12 13:21 UTC
My system is a Archlinux laptop with `pipewire (1.0.6-1)`, `pipewire-pulse (1.0.6-1)` and `pipewire-jack (1.0.7-2)` installed. The installed `raysession` version is `0.14.3-1`.

Because of school I wasn't using my laptop for audio stuff so I haven't opened raysession in a while.
When I opened it today I saw that the patchbay was completely empty. I tried installing `jack2` directly and rebooted, audio was working but still nothing showed up in the patchbay.

I tried other programs like `qpwgraph` and `helvum` and they seemed to show everything, so I am not quite sure what the issue could be.

**Comment by bbeckoo** [comment] 2024-06-14 22:22
Duplicate of https://github.com/Houston4444/RaySession/issues/227

**Comment by bbeckoo** [comment] 2024-06-14 22:23
update https://archlinux.org/packages/extra/x86_64/python-pyalsa/ and you are good to go :)

**Closed** 2024-06-14 22:26 UTC
